const DATABASE_CONNECTION = {
  DATABASE_TEST_CONNECTION: 'DATABASE_TEST_CONNECTION',
  TEST1_COLLECTION: 'test1',
  TEST2_COLLECTION: 'test2',
  TEST3_COLLECTION: 'test3',
  TEST4_COLLECTION: 'test4',
  TEST5_COLLECTION: 'test5'
};

export default DATABASE_CONNECTION;
